-- 코드를 입력하세요
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE PUBLISHED_DATE >= '2021-01-01' and PUBLISHED_DATE< '2022-01-01' and CATEGORY = '인문'
ORDER BY PUBLISHED_DATE ASC